source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ReduxFileLogger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReduxFileLogger
  pod 'ZIPFoundation', '~> 0.9'

end
